// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates personalized thank you note templates based on client inquiry details.
 *
 * - generateThankYouNote - A function that generates thank you note templates.
 * - GenerateThankYouNoteInput - The input type for the generateThankYouNote function.
 * - GenerateThankYouNoteOutput - The return type for the generateThankYouNote function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateThankYouNoteInputSchema = z.object({
  clientName: z.string().describe('The name of the potential client.'),
  weddingDate: z.string().describe('The date of the wedding.'),
  venue: z.string().describe('The wedding venue.'),
  packageOfInterest: z.string().describe('The photography package the client is interested in.'),
  specificRequests: z.string().describe('Any specific requests or details the client mentioned.'),
});
export type GenerateThankYouNoteInput = z.infer<typeof GenerateThankYouNoteInputSchema>;

const GenerateThankYouNoteOutputSchema = z.object({
  thankYouNote: z.string().describe('A personalized thank you note template.'),
});
export type GenerateThankYouNoteOutput = z.infer<typeof GenerateThankYouNoteOutputSchema>;

export async function generateThankYouNote(input: GenerateThankYouNoteInput): Promise<GenerateThankYouNoteOutput> {
  return generateThankYouNoteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateThankYouNotePrompt',
  input: {schema: GenerateThankYouNoteInputSchema},
  output: {schema: GenerateThankYouNoteOutputSchema},
  prompt: `You are a wedding photography studio owner who wants to generate personalized thank you notes for potential clients.

  Based on the information provided, create a warm and inviting thank you note template that encourages them to book your services and gathers more details about their needs.

  Client Name: {{{clientName}}}
  Wedding Date: {{{weddingDate}}}
  Venue: {{{venue}}}
  Package of Interest: {{{packageOfInterest}}}
  Specific Requests: {{{specificRequests}}}

  The thank you note should:
  - Express gratitude for their inquiry.
  - Highlight the studio's expertise in wedding photography.
  - Mention the specific package they are interested in.
  - Acknowledge any specific requests they made.
  - Encourage them to schedule a consultation to discuss their wedding photography needs further.
  - Ask for any further details about their wedding.
  `,
});

const generateThankYouNoteFlow = ai.defineFlow(
  {
    name: 'generateThankYouNoteFlow',
    inputSchema: GenerateThankYouNoteInputSchema,
    outputSchema: GenerateThankYouNoteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
