// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Genera plantillas personalizadas de notas de agradecimiento basadas en los detalles de la consulta del cliente.
 *
 * - generateThankYouNote - Una función que genera plantillas de notas de agradecimiento.
 * - GenerateThankYouNoteInput - El tipo de entrada para la función generateThankYouNote.
 * - GenerateThankYouNoteOutput - El tipo de retorno para la función generateThankYouNote.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateThankYouNoteInputSchema = z.object({
  clientName: z.string().describe('El nombre del cliente potencial.'),
  weddingDate: z.string().describe('La fecha de la boda.'),
  venue: z.string().describe('El lugar de la boda.'),
  packageOfInterest: z.string().describe('El paquete de fotografía en el que el cliente está interesado.'),
  specificRequests: z.string().describe('Cualquier solicitud o detalle específico que el cliente haya mencionado.'),
});
export type GenerateThankYouNoteInput = z.infer<typeof GenerateThankYouNoteInputSchema>;

const GenerateThankYouNoteOutputSchema = z.object({
  thankYouNote: z.string().describe('Una plantilla de nota de agradecimiento personalizada.'),
});
export type GenerateThankYouNoteOutput = z.infer<typeof GenerateThankYouNoteOutputSchema>;

export async function generateThankYouNote(input: GenerateThankYouNoteInput): Promise<GenerateThankYouNoteOutput> {
  return generateThankYouNoteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateThankYouNotePrompt',
  input: {schema: GenerateThankYouNoteInputSchema},
  output: {schema: GenerateThankYouNoteOutputSchema},
  prompt: `Eres el dueño de un estudio de fotografía de bodas que quiere generar notas de agradecimiento personalizadas para clientes potenciales.

  Basándote en la información proporcionada, crea una plantilla de nota de agradecimiento cálida y acogedora que los anime a contratar tus servicios y recopile más detalles sobre sus necesidades. Asegúrate de que la nota esté en español.

  Nombre del Cliente: {{{clientName}}}
  Fecha de la Boda: {{{weddingDate}}}
  Lugar: {{{venue}}}
  Paquete de Interés: {{{packageOfInterest}}}
  Solicitudes Específicas: {{{specificRequests}}}

  La nota de agradecimiento debe:
  - Expresar gratitud por su consulta.
  - Destacar la experiencia del estudio en fotografía de bodas.
  - Mencionar el paquete específico en el que están interesados.
  - Reconocer cualquier solicitud específica que hayan hecho.
  - Animarlos a programar una consulta para discutir más a fondo sus necesidades de fotografía de bodas.
  - Solicitar más detalles sobre su boda.
  `,
});

const generateThankYouNoteFlow = ai.defineFlow(
  {
    name: 'generateThankYouNoteFlow',
    inputSchema: GenerateThankYouNoteInputSchema,
    outputSchema: GenerateThankYouNoteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
